name: template-prod-example

services:
  api:
    build: 
      context: ./api
      target: production
    restart: unless-stopped
    env_file: ./api/.env
    networks:
      -  template-example

  client:
    build: 
      context: ./client
      target: production
      args:
        - VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      -  template-example
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
        - template-example
    depends_on:
      - api
      - client
    
networks:
  template-example:
    driver: bridge