name: template-dev-example

services:

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/data/db
    networks:
      -  template-example
    ports:
      - 5432:5432

  api:
    build: 
      context: ./api
      target: development
    restart: unless-stopped
    env_file: ./api/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - APP_ORIGIN=https://${DOMAIN_NAME}
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      -  template-example
    ports:
      - 4004:4004
    depends_on:
      - db
    command: sh -c "npm run db:migrate && npm run dev"

  client:
    build: 
      context: ./client
      target: development
      args: 
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      -  template-example
    ports:
      - 5173:5173
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - template-example
    depends_on:
      - api
      - client
  
volumes:
  pg_data:
  caddy_data:
  caddy_config:

networks:
  template-example:
    driver: bridge