name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions: 
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Login to the Container registry
      uses: docker/login-action@v3
      with: 
        registry: https://ghcr.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push Client Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./client
        push: true
        tags:
          ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/template-image-client:latest
          ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/template-image-client:${{ github.sha }}
    - name: Build and push API Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./api
        push: true
        tags:
          ghcr.io/eascen-templates/template-image-api:latest
          ghcr.io/eascen-templates/template-image-api:${{ github.sha }}
